version: "3.8"

services:
  main_microservice:
    build: ./src
    ports:
      - "5000:5000"
    environment:
      - ENV=development
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge