version: '3.8'

services:
  main_microservice:
    build: ./Main_microservice
    ports:
      - "5000:3000"

    environment:
      - ENV: development
      - PORT=3000
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}  # Uses .env value or defaults
      - NODE_ENV=production
    volumes:
      - ./Main_microservice:/app  # Changed to be service-specific
    networks:
      - app-network
    depends_on:
      - mongo
    restart: unless-stopped

  2_microservice:
    build: ./2_microservice
    ports:
      - "5001:3001"
    environment:
      ENV: development
    volumes:
      - ./2_microservice:/app  # Changed to be service-specific
    networks:
      - app-network
    depends_on:
      - mongo
    restart: unless-stopped

  3_microservice:
    build: ./3_microservice
    ports:
      - "5002:3002"
    environment:
      ENV: development
    volumes:
      - ./3_microservice:/app  # Changed to be service-specific
    networks:
      - app-network
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:  # Added this section to define named volumes
  mongodb_data: